### PR TITLE
add npm install, lint, test to travis

### PR DESCRIPTION
**Pull request by przemyslawjanpietrzak**

### CODE REVIEW

**Comment by ulfryk** [comment]
npm should automaticly run `npm test`, and it seems to have all that is needed: https://github.com/monet/monet.js/blob/develop/package.json#L32

**Comment by przemyslawjanpietrzak** [comment]
Sorry, i missed that

**Comment by ulfryk** [comment]
Ok, then closing :)

**Comment by przemyslawjanpietrzak** [comment]
Wait wait, my goal was to run `npm test` during creating pull request. I missed that `npm test` calls `npm run build`, so i remove `npm run build` from Travis script

**Pull request closed without merging**
