### PR TITLE
Applicative.apTo method

### PR DESCRIPTION
**Pull request by iLikeKoffee**
Implemented our discussion at https://github.com/monet/monet.js/issues/206

@ulfryk

### CODE REVIEW

**Comment by iLikeKoffee** [comment]
JFYI. Haven't tested this with npm link yet.

**Comment by ulfryk** [comment]
@iLikeKoffee LGTM 👍 

Code looks good! Just please extend docs ;)

**Review by ulfryk — APPROVED** [review]

**Review by ulfryk — APPROVED** [review]
👍 LGTM 👍

**Comment by ulfryk** [comment]
@iLikeKoffee I'll try to release patch during weekend

**Comment by iLikeKoffee** [comment]
Great! Haven't you got any kind of roadmap? I would gladly contribute)

**Comment by ulfryk** [comment]
@iLikeKoffee - this is future of this library (if I find contributors / supporters): https://github.com/monet/monet

If you would like to help - let's somehow get in touch :)

( fyi: @overflowz )

**Comment by overflowz** [comment]
I'm way too busy at the moment and might be slow to respond/contribute, but if you guys need some help, always feel free to ping me, and will do as soon as I can.

**Pull request merged**
